mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('polls.views',
	url(r'^polls/$', 'index'),
	url(r'^polls/(?P<poll_id>\d+)/$', 'details'),
	url(r'^polls/(?P<poll_id>\d+)/results/$', 'results'),
	url(r'^polls/(?P<poll_id>\d+)/vote/$', 'vote'),
)

urlpatterns += patterns('',
	url(r'^admin/doc/', include(admin.site.urls)),
	url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('blog.views',
	url(r'^$', 'home'),
	url(r'^blog/$', 'blog'),
	url(r'^blog/create/$', 'blog_post'),
	url(r'^test/$', 'current'),
	url(r'^test2/$', 'display_meta'),
	url(r'^search/$', 'search'),
	url(r'^contact/$', 'contact'),
#	url(r'^posts/(?P<y>\d{4})/$', 'year_archive')
	url(r'^eugene/$', 'eugene_archive'),

#	Generic Views
	url(r'^links/$', direct_to_template, {
		'template': 'links.html'
	}),	
	url(r'^blog/save/$', direct_to_template, {
		'template': 'blog_form_save.html'
	}),

)

urlpatterns += patterns('contact.views',
	url(r'^contact_list/$', 'contact_list'),
	url(r'^contact_list/add/$', 'contact_list_add'),
	url(r'^contact_list/save/$', 'contact_list_save'),
)

urlpatterns += patterns('vocab.views',
	url(r'^vocab/$', 'vocab_list'),
	url(r'^vocab/add/$', 'vocab_list_add'),
	url(r'^vocab/save/$', 'vocab_list_save'),
)

urlpatterns += patterns('maps.views',
	url(r'^maps/nyc_electric/$', 'nyc_electric'),
)

urlpatterns += patterns('tasks.views',
	url(r'^tasks/$', 'tasks_list'),
)

urlpatterns += patterns('resume.views',
	url(r'^resume/$', 'resume_content'),
)

urlpatterns += patterns('walkman.views',
	url(r'^walkman/draganddrop/$', 'draganddrop'), 
)

blog/models.py
from django.db import models
from django.contrib import admin

class Author(models.Model):
	name = models.CharField(max_length=64)
	email = models.CharField(max_length=64)

	def __str__(self):
		return "%s (%s)" % (self.name, self.email)

class Post(models.Model):
	title = models.CharField(max_length=64)
	date = models.DateTimeField()
	author = models.ForeignKey(Author)
	body = models.TextField()

	def __str__(self):
		return "%s (%s)" % (self.title, self.author.name)

class PostAdmin(admin.ModelAdmin):
	list_display = ('title', 'date', 'author')

admin.site.register(Post, PostAdmin)

contact/models.py
from django.db import models
from django.contrib import admin

class Contact(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	birthday = models.DateTimeField()
	company = models.CharField(max_length=100)	
	context = models.TextField('Intro Context')

	def __str__(self):
		return "%s %s" % (self.first_name, self.last_name)	

admin.site.register(Contact)

blog/forms.py
from django import forms
from django.forms import ModelForm
from blog.models import *

class ContactForm(forms.Form):
	subject = forms.CharField(max_length=100)
	email = forms.EmailField(required=False)
	message = forms.CharField(widget=forms.Textarea)

	def clean_message(self):
		message = self.cleaned_data['message']
		num_words = len(message.split())
		if num_words < 4:
			raise forms.ValidationError("Not enough words!")
		return message

class AuthorForm(ModelForm):
	class Meta:
		model = Author

class BlogForm(ModelForm):
	class Meta:
		model = Post

contact/forms.py
from django import forms
from django.forms import ModelForm
from contact.models import *

class ContactListForm(ModelForm):
	class Meta:
		model = Contact

blog/views.py
from django.shortcuts import render_to_response
from blog.models import Post, Author
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from blog.forms import ContactForm, BlogForm

def home(request):
	return render_to_response('home_body.html', context_instance=RequestContext(request))

def blog(request):
	all_posts = Post.objects.all().order_by('-date')
	template_data = {'posts' : all_posts}

	return render_to_response('blog.html', context_instance=RequestContext(request, template_data))

def current(request):
	return HttpResponse("Welcome to the test page at %s" % request.path)

def display_meta(request):
	values = request.META.items()
	values.sort()
	html = []
	for k, v in values:
		html.append('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
	return HttpResponse('<table>%s</table>' % '\n'.join(html))

def search(request):
	errors = []
	if 'q' in request.GET:
		q = request.GET['q']
		if not q:
			errors.append('Enter a search term.')
		elif len(q)>20:
			errors.append('Please enter no more than 20 characters')
		else:
			posts = Post.objects.filter(title__icontains=q)
			return render_to_response('search_results.html', {'posts': posts, 'query': q})
	return render_to_response('search_form.html', {'errors': errors})

def contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			send_mail(
				cd['subject'],
				cd['message'],
				cd.get('email', 'noreply@example.com'),
				['siteowner@example.com'],
			)
			return HttpResponseRedirect('/contact/thanks/')
	else:
		form = ContactForm(
			initial={'subject': 'I love your blog!'}
		)
	return render_to_response('contact_form.html', context_instance=RequestContext(request, {'form': form}))

def year_archive(request, y):
	return Post.objects.filter(Post__date__year=y)

def eugene_archive(request):
	return HttpResponse(Post.objects)

def blog_post(request):
	if request.method == 'POST':
		form = BlogForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/blog/save/')
	else:
		form = BlogForm()
	return render_to_response('blog_form.html', {'form': form}, context_instance=RequestContext(request))

contact/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponse, HttpResponseRedirect 
from django.template import RequestContext
from contact.forms import ContactListForm
from contact.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def contact_list(request):
	all_contacts = Contact.objects.all().order_by('last_name')
	paginator = Paginator(all_contacts, 3)
	page = request.GET.get('page')
	try:
		contacts = paginator.page(page)
	except PageNotAnInteger:
		contacts = paginator.page(1)
	except EmptyPage:
		contacts = paginator.page(paginator.num_pages)
	return render_to_response('contact_page.html', context_instance=RequestContext(request, {"contacts": contacts}))

def contact_list_add(request):
	if request.method == 'POST':
		form = ContactListForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/contact_list/save/')
	else:
		form = ContactListForm()
	return render_to_response('contact_list_add.html', {'form': form}, context_instance=RequestContext(request))

def contact_list_save(request):
	return render_to_response('contact_list_save.html', context_instance=RequestContext(request))

blog/templates/blog.html
<html>
	{% extends "home_page.html" %}
	{% block content %}
<head>
	<title>Eugene's Blog</title>
	<link rel="stylesheet" href="{{ STATIC_URL }}blog.css">
</head>
<body>
	<div class="blog-box">
	<br>
	<h1 class="blog-head">Eugene's Blog</h1>
	<br>
	{% for p in posts %}
		<div class="line"><span>{{p.date}}</span></div>
		<h1>{{p.title}}</h1>
		<h2>Written by {{p.author.name}} on {{p.date}} </h2>
		<p>{{ p.body }}</p>
	{% endfor %}
	</div>
	{% endblock %}
</body>
</html>

blog/templates/blog_form.html
<html>

<head>
	{% extends "home_page.html" %}
	{% block content %}
	<title>Blog Post</title>
	<link rel="stylesheet" href="{{ STATIC_URL }}blog_form.css">
</style>	

</head>

<body>
	<h1>Blog Post</h1>
	<div class="blog">	
	<form action="" method="post">{% csrf_token %}
		<ul>
			<ul class="field">Title: {{ form.title }}</ul>
			<ul class="field">Date: {{ form.date }}</ul>
			<ul class="field">Author: {{ form.author }}</ul>
			<ul class="field">Body: {{ form.body }}</ul>
		</ul>
	<br>
	<input class="button" type="submit" value="Save Post">	
	</form>
	</div>
	{% endblock %}
</body>
	
</html>

blog/templates/blog_form_save.html
<html>
<head>
</head>
<body>
	{% extends "home_page.html" %}
	{% block content %}
	<p>Blog Post Saved!</p>
	<a href="http://127.0.0.1:8000/blog">Go to Blog</a> 
	{% endblock %}
</body>
</html>

blog/templates/contact_form.html
<html>
<head>
	<title>Contact Me</title>

<style type="text/css">

.field {
	text-align:left;
	padding-left:10px;
}

</style>

</head>
<body>
	{% extends "home_page.html" %}
	{% block content %}
	<h1>Contact Me!</h1>
	{% if form.errors %}
		<p style="color: red;">
			Please correct the error{{ form.errors|pluralize }} below.
		</p>
	{% endif %}
	<form action="" method="post">
		<div class="field">
			{{ form.subject.errors }}
			<label for="id_subject">Subject:</label>
			{{ form.subject }}
		</div>
		<div class="field">
			{{ form.email.errors }}
			<label for="id_email">Your e-mail address:</label>
			{{ form.email }}
		</div>
		<div class="field">
			{{ form.message.errors }}
			<label for="id_message">Message:</label>
			{{ form.message }}
		</div>
		<input type="submit" value="Submit">
	</form>
	{% endblock %}
</body>
</html>

blog/templates/home_body.html
<html>
<head>
<style type="text/css">


</style>
</head>
<body>
	{% extends "home_page.html" %}
	{% block content %}
		<p>Hello World!</p>
	{% endblock %}
</body>
</html>

blog/templates/home_page.html
<html>

<head>
	<title>Eugene Wang</title>
	<link rel="stylesheet" href="{{ STATIC_URL }}home_css.css">
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.4.1-vsdoc.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}home_js.js"></script>
</head>

<body>
	<div id="header">
	<p class="title">Eugene Wang</p>
	<p class="sub-title">"Not all who wander are lost"</p>
	</div>
	<br>
	<div class="wrap">
		<div id="nav">
		<ul><a href="http://127.0.0.1:8000/">HOME</a></ul>
		<ul><a href="http://127.0.0.1:8000/resume/">RESUME</a></ul>
		<ul><a href="http://127.0.0.1:8000/blog/">BLOG</a></ul>
		<ul><a href="http://127.0.0.1:8000/links/">LINKS</a></ul>
		<ul><a href="http://127.0.0.1:8000/contact_list/">CONTACTS</a></ul>
		<ul><a href="http://127.0.0.1:8000/tasks/">TASKS</a></ul>
		<ul><a href="http://127.0.0.1:8000/contact/">SEND A NOTE!</a></ul>
		<ul><a href="http://127.0.0.1:8000/vocab/">VOCAB LIST</a></ul>
		<ul><a href="http://127.0.0.1:8000/maps/nyc_electric/">MAPS</a></ul>
		</div>
		<div id="main">
			{% block content %}
			{% endblock %}
		</div>
		<div id="sidebar">
			<form action="http://127.0.0.1:8000/blog/create/">
			<input type="submit" class="button" value="Create Blog Post">
			</form>
			<form action="http://127.0.0.1:8000/contact_list/add/">
			<input type="submit" class="button" value="Add a Contact">
			</form>
			<form action="http://127.0.0.1:8000/vocab/add/">
			<input type="submit" class="button" value="Add a Vocab Word">
			</form>
		</div>
		<div id="footer">
			<form action="http://127.0.0.1:8000/admin/">
			<input type="submit" value="Go To Admin Site">
		</div>
	</div>
</body>
</html>

blog/templates/index.html
<html>
<head>
<title>
Eugene's Blog
</title>

<style type='text/css'>

h1 {
	color:blue;
	text-align:left;
	font-size:20px;
	padding-left:10px;
}

h2 {
	color:green;
	text-align:left;
	font-size:16px;
	padding-left:10px;
}

p {
	color:black;
	text-align:left;
	font-size:12px;
	margin: lem 0;
	padding-left:10px;
}

</style>

</head>
<body>
	{% extends "home_page.html" %}
	{% block content %}
	{% for p in posts %}
		<h1>{{p.title}}</h1>
		<h2>Written by {{p.author.name}} on {{p.date}} </h2>
		<p>{{ p.body }}</p>
		<br>
		
	{% endfor %}
	{% endblock %}
</body>
</html>

blog/templates/links.html
<html>
	{% extends "home_page.html" %}
	{% block content %}
		<h1>My Favorite Links</h1>
		<ul>
			<p><a href="http://www.espn.com">ESPN</a></p>
			<p><a href="http://www.wikipedia.com">Wikipedia</a></p>
			<p><a href="http://www.blackstone.com">Blackstone</a></p>
		</ul>
	{% endblock %}
</html>

blog/templates/search_form.html
<html>
<head>
	<title>Search Form</title>
</head>
<body>
	{% if errors %}
		<p 
		<br>	
Please submit a search term</p>
		<ul>
			{% for error in errors %}
			<li>{{ error }}</li>
			{% endfor %}
		</ul>
	{% endif %}
	<p style="font-size:50px; text-align:center"><strong>Search Eugene's Blog</strong></p>
	<form action="" method="get" style="text-align:center; margin-top:10px">
		<input type = "text" name="q">
		<input type="submit" value="Search">
	</form>
</body>
</html>

blog/templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if posts %}
	<p>Found {{ posts|length }} post{{posts|pluralize }}.</p>
	<ul>
		{% for post in posts %}
		<li><strong>{{ post.title }}</strong></li>
		<li>{{ post.author }}</li>
		<li>{{ post.date }}</li>
		<br>
		{% endfor %}
		</ul>
{% else %}
	<p>No posts matched your search criteria.</p>
{% endif %}